repos:
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.45.0
    hooks:
      - id: markdownlint
        args: ['--fix']
        exclude: '^(CHANGELOG\.md|README\.md|LICENSE\.md)$'
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: '\.md$'  # Let markdownlint handle markdown files
  # Local hooks for project-specific checks
  - repo: local
    hooks:
      - id: check-prp-status
        name: Check for IN_PROGRESS PRPs
        entry: python scripts/check_prp_status.py
        language: python
        files: ^PRPs/.*\.md$
        pass_filenames: true
        verbose: true
