openapi: 3.0.0
info:
  title: CC-Boilerplate Recovery System API
  version: 1.0.0
  description: API for mid-journey course correction and state recovery

paths:
  /recovery/checkpoints:
    get:
      summary: List recovery checkpoints
      operationId: listCheckpoints
      responses:
        '200':
          description: List of checkpoints
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RecoveryCheckpoint'

    post:
      summary: Create recovery checkpoint
      operationId: createCheckpoint
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                type:
                  type: string
                  enum: [manual, auto, pre_operation]
                reason:
                  type: string
              required:
                - type
                - reason
      responses:
        '201':
          description: Checkpoint created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RecoveryCheckpoint'

  /recovery/checkpoints/{checkpointId}/restore:
    post:
      summary: Restore from checkpoint
      operationId: restoreCheckpoint
      parameters:
        - name: checkpointId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                preserveUncommitted:
                  type: boolean
                  default: true
                restoreWorkflows:
                  type: boolean
                  default: false
      responses:
        '200':
          description: Restore completed
          content:
            application/json:
              schema:
                type: object
                properties:
                  restored:
                    type: object
                    properties:
                      branch:
                        type: string
                      commit:
                        type: string
                      files:
                        type: array
                        items:
                          type: string
                  preserved:
                    type: array
                    items:
                      type: string

  /recovery/git/smart-commit:
    post:
      summary: Split mixed changes into logical commits
      operationId: smartCommit
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                analyze:
                  type: boolean
                  default: true
                  description: Analyze changes before committing
      responses:
        '200':
          description: Commits created
          content:
            application/json:
              schema:
                type: object
                properties:
                  analysis:
                    type: object
                    properties:
                      features:
                        type: array
                        items:
                          type: object
                          properties:
                            name:
                              type: string
                            files:
                              type: array
                              items:
                                type: string
                  commits:
                    type: array
                    items:
                      type: object
                      properties:
                        hash:
                          type: string
                        message:
                          type: string
                        files:
                          type: integer

  /recovery/git/workflow-repair:
    post:
      summary: Repair git workflow issues
      operationId: repairWorkflow
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                issue:
                  type: string
                  enum: [wrong_branch, mixed_commits, merge_conflict, detached_head]
      responses:
        '200':
          description: Workflow repaired
          content:
            application/json:
              schema:
                type: object
                properties:
                  originalState:
                    type: object
                  repairedState:
                    type: object
                  actions:
                    type: array
                    items:
                      type: string

  /recovery/spec/backfill:
    post:
      summary: Generate missing specifications from code
      operationId: backfillSpec
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                path:
                  type: string
                  description: Code path to analyze
                type:
                  type: string
                  enum: [prp, spec, adr]
      responses:
        '200':
          description: Specification generated
          content:
            application/json:
              schema:
                type: object
                properties:
                  generated:
                    type: string
                    description: Path to generated specification
                  extracted:
                    type: object
                    properties:
                      requirements:
                        type: array
                        items:
                          type: string
                      architecture:
                        type: object
                      decisions:
                        type: array
                        items:
                          type: string

components:
  schemas:
    RecoveryCheckpoint:
      type: object
      properties:
        id:
          type: string
        timestamp:
          type: string
          format: date-time
        type:
          type: string
          enum: [manual, auto, pre_operation]
        state:
          type: object
          properties:
            git:
              type: object
              properties:
                branch:
                  type: string
                commit:
                  type: string
                uncommitted:
                  type: array
                  items:
                    type: string
            workflows:
              type: object
              properties:
                active:
                  type: array
                  items:
                    type: string
                queued:
                  type: array
                  items:
                    type: string
            agents:
              type: object
              properties:
                active:
                  type: array
                  items:
                    type: string
        metadata:
          type: object
          properties:
            reason:
              type: string
            user:
              type: string
            expires:
              type: string
              format: date-time