openapi: 3.0.0
info:
  title: CC-Boilerplate Workflow Management API
  version: 1.0.0
  description: API for managing and executing workflows in the CC-Boilerplate framework

paths:
  /workflows:
    get:
      summary: List all workflows
      operationId: listWorkflows
      responses:
        '200':
          description: List of workflows
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Workflow'

    post:
      summary: Create new workflow
      operationId: createWorkflow
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WorkflowCreate'
      responses:
        '201':
          description: Workflow created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Workflow'
        '400':
          description: Invalid workflow definition

  /workflows/{workflowId}/execute:
    post:
      summary: Execute workflow
      operationId: executeWorkflow
      parameters:
        - name: workflowId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                input:
                  type: object
                  description: Workflow input data
      responses:
        '200':
          description: Workflow execution started
          content:
            application/json:
              schema:
                type: object
                properties:
                  executionId:
                    type: string
                  status:
                    type: string
                    enum: [pending, running, completed, failed]
        '403':
          description: Security validation required

  /workflows/executions/{executionId}:
    get:
      summary: Get workflow execution status
      operationId: getExecution
      parameters:
        - name: executionId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Execution details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkflowExecution'

components:
  schemas:
    Workflow:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        trigger:
          type: string
          enum: [manual, command, event, schedule]
        stages:
          type: array
          items:
            $ref: '#/components/schemas/WorkflowStage'
        security:
          type: object
          properties:
            requiresChain:
              type: boolean
            auditLevel:
              type: string
              enum: [none, basic, comprehensive]
        timeout:
          type: integer
          description: Maximum execution time in seconds
      required:
        - name
        - trigger
        - stages

    WorkflowCreate:
      type: object
      properties:
        name:
          type: string
        trigger:
          type: string
          enum: [manual, command, event, schedule]
        stages:
          type: array
          items:
            $ref: '#/components/schemas/WorkflowStage'
        security:
          type: object
          properties:
            requiresChain:
              type: boolean
            auditLevel:
              type: string
              enum: [none, basic, comprehensive]
      required:
        - name
        - trigger
        - stages

    WorkflowStage:
      type: object
      properties:
        name:
          type: string
        agent:
          type: string
        input:
          type: object
        validation:
          type: array
          items:
            type: object
            properties:
              condition:
                type: string
        onSuccess:
          type: string
          description: Next stage name
        onFailure:
          type: string
          description: Error handling stage
      required:
        - name
        - agent

    WorkflowExecution:
      type: object
      properties:
        id:
          type: string
        workflowId:
          type: string
        status:
          type: string
          enum: [pending, running, completed, failed]
        startTime:
          type: string
          format: date-time
        endTime:
          type: string
          format: date-time
        stages:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
              status:
                type: string
                enum: [pending, running, completed, failed, skipped]
              result:
                type: object
              error:
                type: string